---
- name: create folder
  file:
    path: /opt/hugo
    owner: root
    group: root
    state: directory

- name: Install hugo
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - hugo

- name: Git clone photo-gallery
  git:
    repo: https://github.com/ErickHunter/photo-gallery.git
    dest: /opt/hugo
    version: master
    update: yes
  environment:
    GIT_TERMINAL_PROMPT: 0 # reports "terminal prompts disabled" on missing password
    # or GIT_ASKPASS: /bin/true # for git before version 2.3.0, reports "Authentication failed" on missing password
  notify:
    - Rebuild hugo
